### ISSUE TITLE
Update to JMeter 5.4

### ISSUE THREAD

**Issue by ankugarg** [abstracta/jmeter-java-dsl#11]
Can you please to JMeter 5.4?

**Comment by rabelenda** [comment]
Hello, thank you for the request. 

We are evaluating doing the migration (there are pros & cons).

Do you have any particular reason/request/requirement that would be satisfied by moving the project to Jmeter 5.4?

Please, if anyone else have reasons or just think this would be interesting, give feedback and we will prioritize this item higher.

Regards

**Comment by ankugarg** [comment]
Thanks for responding.

I want to test Graphql which is supported by this version.

**Comment by rabelenda** [comment]
Hello,

Thank you for sharing your needs, that clarifies a lot and helps us prioritize work to be done.

As far as I understand JMeter 5.4 only provides easier means (over previous versions) to edit and define GraphQL requests in JMeter GUI, but has no change in the underneath/core logic required to send GraphQL requests (it just uses the existing http sampler without any alteration). You should be able to generate GraphQL requests with existing httpSampler method in jmeter-java-dsl. Here is an example:

```java
import static org.assertj.core.api.Assertions.assertThat;
import static us.abstracta.jmeter.javadsl.JmeterDsl.*;

import java.io.IOException;
import java.time.Duration;
import org.eclipse.jetty.http.MimeTypes.Type;
import org.junit.jupiter.api.Test;
import us.abstracta.jmeter.javadsl.core.TestPlanStats;

public class PerformanceTest {

  @Test
  public void testPerformance() throws IOException {
    TestPlanStats stats = testPlan(
      threadGroup(1, 1,
        httpSampler("https://api.github.com/graphql")
          .post("{\"query\":\"query { "
                + "repository(owner:\\\"octocat\\\", name:\\\"Hello-World\\\") { "
                  + "issues(last:20, states:CLOSED) { "
                    + "edges { "
                      + "node { "
                        + "title "
                        + "url "
                        + "labels(first:5) { "
                          + "edges { "
                            + "node { "
                              + "name "
                            + "} "
                          + "} "
                        + "} "
                      + "} "
                    + "} "
                  + "} "
                + "} "
              + "}\" }", Type.TEXT_PLAIN)
            .header("Authorization", "Bearer XXX")
      )
    ).run();
    assertThat(stats.overall().elapsedTimePercentile99()).isLessThan(Duration.ofSeconds(5));
  }

}
```

Do you have any particular need or idea regarding GraphQL that requires migrating to JMeter 5.4? How were you planning to use jmeter-java-dsl for GraphQL requests (maybe give some pseudo code on how you planned to use it)?

Regards

**Comment by ankugarg** [comment]
Above code resolves my query.
Thanks for sharing detailed example, it's really helpful.

**Comment by rabelenda** [comment]
I am glad that the example is helpful.

You might consider using something like [this](https://github.com/k0kubun/graphql-query-builder) to build the query instead of using a plain string, or maybe use some more advanced way with [graphql java library](https://www.graphql-java.com/documentation/v16/getting-started/).

Regards
