### ISSUE TITLE
Upgrading JMeter to 5.5 - fixing CVE vulnerabilities

### ISSUE THREAD

**Issue by dmi3bk** [abstracta/jmeter-java-dsl#128]
The current version 5.4.3 has 18 vulnerabilities, so it's a bit risky to use in cloud environment
![image](https://user-images.githubusercontent.com/96298070/180871444-b218ba60-8e42-4892-8cab-d02736f7c289.png)

**Comment by rabelenda** [comment]
Hello, thank you for asking for this. Several of such vulnerabilities have been fixed by upgrading corresponding dependencies in JMeter DSL (you might check https://github.com/abstracta/jmeter-java-dsl/issues/94). In any case we will work on upgrading JMeter to 5.5 to improve this.

Regards

**Comment by dmi3bk** [comment]
Hi @rabelenda,

I need to use `jmeter-java-dsl` with `DistributedJmeterEngine` (cluster of slaves).
As I understand correctly, `jmeter-java-dsl` tests (and dependencies) should be added as `libs` into jmeter slaves - but we cannot pass `trivy` checks for such bundle.

Regards,
Dmitry

**Comment by dmi3bk** [comment]
BTW, can you please share any `docker-compose` how to setup distributed jmeter? I cannot find any good examples for it.

**Comment by rabelenda** [comment]
Hello,

Depending on the components you use you might need or not to add jmeter-java-dsl and dependencies into slaves, but if you just need to test HTTP endpoints, you should not be required to do any setup steps (copying files to slaves).

We have just released a [new version of DSL](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.64) that uses JMeter 5.5 and have also included an [example of using distributed engine with docker-compose](https://github.com/abstracta/jmeter-java-dsl/tree/master/docs/guide/distributed). I hope it helps.

Regards

**Comment by dmi3bk** [comment]
Thanks a lot, @rabelenda! 
This update to `5.5` was blazingly fast comparing to other open-source frameworks.
