### ISSUE TITLE
Validating HTTP Status Code

### ISSUE THREAD

**Issue by aabirdaneshyar** [abstracta/jmeter-java-dsl#14]
Hello,

Can we validate HTTP Status Code using this library. The idea is that test case should fail if we get HTTP status code other than 2XX (Other stats should not matter in this case).

Regards
Aabir

**Comment by rabelenda** [comment]
Hello,

The library automatically marks any HTTP request that gets a response code other than 2xx (successes) and 3xx (redirects) as failure. This is a consequence of the library just being a handy way of using JMeter in a programmatic fashion. 

If you want to change that, you can use [response assertions](https://github.com/abstracta/jmeter-java-dsl/blob/master/docs/use-cases.md#check-for-expected-response) or [post processors](https://github.com/abstracta/jmeter-java-dsl/blob/master/docs/use-cases.md#change-sample-result-statuses-with-custom-logic).

Can you describe better what you intent to do, so I may give you a better answer?

Side note: Take into consideration that the main purpose of the library is for running performance tests, even though you might use it for other purposes (eg: automated functional tests).

**Comment by aabirdaneshyar** [comment]
Thanks for quick reply.

My test scenario is as follows -
Response time of a given API with thread count 100 should be less than 2 seconds. 

Also, it would be nice to check for the response code. 

Regards
Aabir

**Comment by rabelenda** [comment]
Hello,

For both cases you can use response assertions to mark requests as failure when any of the conditions aren't met, and then use resulting statistics to verify there are no requests marked as error.

Do you think this satisfies your needs? If not, please let me know.

Regards

**Comment by aabirdaneshyar** [comment]
Thanks a lot. This worked for me.
