### ISSUE TITLE
git tag does not match release

### ISSUE THREAD

**Issue by hboutemy** [abstracta/jmeter-java-dsl#150]
release 1.0.1 was just done, and is expected to be reproducible thanks to #144 

but I just found that v1.0.1 tag does not builds version 1.0.1 but 0.1-SNAPSHOT: https://github.com/abstracta/jmeter-java-dsl/blob/03b13e109a886954318117cf8a157089551dc694/pom.xml (and same for the source .zip https://github.com/abstracta/jmeter-java-dsl/releases/tag/v1.0.1 )

then it's impossible to rebuild from source... :(

why don't you commit content before tagging?
making your build reproducible will require a change to your release process

**Comment by hboutemy** [comment]
notice that I was able to create the source in my fork: https://github.com/hboutemy/jmeter-java-dsl/commit/145f9600ae8150ca1bde55815377904a7568f483

using my fork, I can reproduce your official build: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/us/abstracta/jmeter/jmeter-java-dsl/README.md

the only missing part for all that reproducible build is the commit in your own original Git repository associated to the v1.0.1 tag

**Comment by rabelenda** [comment]
Hello, thank you for reporting this and taking the time to verify it and check the root souce.

Currently the release process is as is, and sacrifices tag to be exaclty the same as release version (the only difference is the setting of version with `mvn versions:set -DnewVersion=X`), to make it supper simple to create and trigger.

Nowadays release process is quite simple and intuitive: just going to GH releases, create a new draft, fill version number and description and then publish, then everything gets released. Additionally, minimal commits are included in git for the release (just 1).

I will review options to keep release process simple (1 manual release step) and see if we can get exact same tagged code as the one released.

I am considering right now manual trigger of github workflow requiring inputs (version and release description). Which then triggers a pipeline that changes version, update docs, tags, releases/publishes, create GH release, changes version to a SNAPSHOT version.

Does anyone have other ideas?

**Comment by rabelenda** [comment]
Hello, 

Can you check the [new release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v1.0.2)?

The release process is not as simple as it used to be, but I think it is a good trade off to get better traceability between source code and binaries.

Regards

**Comment by hboutemy** [comment]
great job, it's a full success: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/us/abstracta/jmeter/jmeter-java-dsl/README.md

now it's time to proudly wear your badge #152 :)
