### ISSUE TITLE
API to save response body

### ISSUE THREAD

**Issue by gunnu-smile** [abstracta/jmeter-java-dsl#17]
Can you please provide API to save response body?

It would be helpful to analyze issues when something goes wrong with application under test.

**Comment by rabelenda** [comment]
Sure!

Currently the only way jmeter-java-dsl provides to do this (you may use it in the mean time) is using a jsr223PostProcessor and save the response bodies to a file and format of your preference.

eg:

```java
testPlan(
        threadGroup(1, 10,
            httpSampler("https://abstracta.us")
              .children(
                  jsr223PostProcessor("new File('traceFile') << \"${prev.sampleLabel}>>${prev.responseDataAsString}\\n\"")
              )
        )
    ).run();
```

In future release we will include JMeter provided feature to allow saving in jtl (in xml format) additional information, as request & response bodies & headers. This will allow you to easily visualize information in JMeter GUI if needed.

Regards

**Comment by gunnu-smile** [comment]
Thanks.

**Comment by rabelenda** [comment]
Check [latest release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.13) and [new use cases section](https://github.com/abstracta/jmeter-java-dsl/blob/v0.13/docs/use-cases.md#log-requests-and-responses) for additional new options.

Regards
