### ISSUE TITLE
GraphqlSampler doesn't support GET requests

### ISSUE THREAD

**Issue by OlegDementyevInDrive** [abstracta/jmeter-java-dsl#171]
Hello!

In my test I send the GraphQL GET-requests. Jmeter GUI supports both types of requests (GET and POST), but in Jmeter-Java-DSL I can send only POST-request as default and I can't send the GET-request. GraphqlSampler().method() is absence. Could you add this option?

**Comment by rabelenda** [comment]
Hello, thanks for asking for this feature!

Yesterday we released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v1.7) which includes `httpGet()` method in the sampler which should allow you to use HTTP Get method.

Please try it and let us know of any potential improvements.

Regards
