### ISSUE TITLE
JmeterDSL inside SpringBoot Application. java.nio.file.NoSuchFileException: /bin

### ISSUE THREAD

**Issue by sial** [abstracta/jmeter-java-dsl#174]
Hi!

I encountered the problem using JmeterDSL 1.7
Library could not find /bin directory in JmeterEnvinroment Class

![telegram-cloud-photo-size-2-5454235959567697918-y](https://user-images.githubusercontent.com/11280681/220709063-71fe2baa-0400-4173-bf64-0f26bc9892e4.jpg)

![telegram-cloud-photo-size-2-5456235129405030929-y](https://user-images.githubusercontent.com/11280681/220714130-6055aed7-fd30-41fc-bc0d-906c655a6779.jpg)

InstallConfig method contains hardcoded path "/" on 92 line

**Comment by rabelenda** [comment]
Hello, thank you for reporting this!

Can you share the full stack trace?

Regards

**Comment by sial** [comment]
I don't know, mb it is connected with class path?

![Screenshot 2023-02-27 at 11 33 44](https://user-images.githubusercontent.com/11280681/221541139-f7090364-857d-447b-87b6-30be1e2db834.png)

**Comment by sial** [comment]
Seems that it could not find /bin directory in jar to copy it to target path during installConfig method

**Comment by rabelenda** [comment]
Are you trying to repackage Jmeter dsl inside another jar? I see some tomcat and spring framework references in the stack trace, like you packaged jmeter dsl inside a spring application.

If that is the case, you have to be careful so as for bin folder to be included in final jar, otherwise you might lose it and get such error.

When you say you exec as jar... what jar are you actually executing? is that a spring boot app that you are trying to run from the jar? You might need to tune spring boot packaging maven/gradle plugin to get bin directory properly placed and solved on it.

Maybe if you can share some code on how you are using the DSL, maybe a sample project that has similar structure as the one you are using, or the exact same code, we might be able to help you further.

**Comment by rabelenda** [comment]
Here is a spring boot related discussion, maybe this helps you: https://github.com/abstracta/jmeter-java-dsl/issues/147

**Comment by sial** [comment]
```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <layout>ZIP</layout>
        <requiresUnpack>
            <dependency>
                <groupId>us.abstracta.jmeter</groupId>
                <artifactId>jmeter-java-dsl</artifactId>
            </dependency>
        </requiresUnpack>
    </configuration>
</plugin>

```

Did not help

**Comment by sial** [comment]
> Maybe if you can share some code on how you are using the DSL, maybe a sample project that has similar structure as the one you are using, or the exact same code, we might be able to help you further.

Here is a simple demo. Build Jar using maven by mvn clean package
[JmeterDSLTest.zip](https://github.com/abstracta/jmeter-java-dsl/files/10842086/JmeterDSLTest.zip)

**Comment by rabelenda** [comment]
You need to unpack dependencies that contain JMeter components as well, as the example provided in the issue I passed.

Can you try with something like this?:

```xml
<requiresUnpack>
                        <dependency>
                            <groupId>us.abstracta.jmeter</groupId>
                            <artifactId>jmeter-java-dsl</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>org.apache.jmeter</groupId>
                            <artifactId>ApacheJMeter_components</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>org.apache.jmeter</groupId>
                            <artifactId>ApacheJMeter_config</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>org.apache.jmeter</groupId>
                            <artifactId>ApacheJMeter_core</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>org.apache.jmeter</groupId>
                            <artifactId>ApacheJMeter_functions</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>org.apache.jmeter</groupId>
                            <artifactId>ApacheJMeter_http</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>org.apache.jmeter</groupId>
                            <artifactId>ApacheJMeter_java</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>kg.apc</groupId>
                            <artifactId>jmeter-plugins-casutg</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>kg.apc</groupId>
                            <artifactId>jmeter-plugins-dummy</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>kg.apc</groupId>
                            <artifactId>jmeter-plugins-tst</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>com.blazemeter</groupId>
                            <artifactId>jmeter-plugins-random-csv-data-set</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>com.blazemeter</groupId>
                            <artifactId>jmeter-plugins-wsc</artifactId>
                        </dependency>
                    </requiresUnpack>
```

**Comment by sial** [comment]
I wish to express my appreciation for all your efforts. I am truly grateful for your advice and help. Thank you so much for this tool! Everything is working!

**Comment by rabelenda** [comment]
Thank you very much for your words @sial. 

I am glad that everything worked only with that change and that you can enjoy the tool and find it helpful. 

Regards
