### ISSUE TITLE
Add aggregate report listener support

### ISSUE THREAD

**Issue by andy-tarr** [abstracta/jmeter-java-dsl#179]
Add the aggregate report listener to the dsl

**Comment by rabelenda** [comment]
@andy-tarr do you haven any further insights here? Otherwise I will close this issue.

**Comment by andy-tarr** [comment]
Happy for this to be closed.
Thanks

Sent from my iPhone

On 4 Aug 2023, at 19:03, rabelenda ***@***.***> wrote:

﻿

@andy-tarr<https://github.com/andy-tarr> do you haven any further insights here? Otherwise I will close this issue.
