### ISSUE TITLE
Jmeter Test plan and execution

### ISSUE THREAD

**Issue by sangamthakur-sec** [abstracta/jmeter-java-dsl#18]
Great tool. Is it possible All the things we can do with JMeter can be done with JMeter-java-DSL?

**Comment by rabelenda** [comment]
Thank you very much.

In theory yes, but currently the api is limited to the most used cases and what users have requested. 

If you are in need of something the api doesn't still support ,please create an issue requesting it and with some explanation why is needed, and we will be very glad and eager to implement it (usually is quite fast to implement support for new jmeter features).

You can also easily implement (if you have enough programmatic and jmeter knowledge) new missing features in the dsl. You can check the [Contributing](https://github.com/abstracta/jmeter-java-dsl/blob/master/CONTRIBUTING.md) document for a quick intro.

Regards

**Comment by sangamthakur-sec** [comment]
Thanks
