### ISSUE TITLE
Sending Test Results to DataDog

### ISSUE THREAD

**Issue by uddirulz** [abstracta/jmeter-java-dsl#199]
Hi,

Opening another request to support sending dsl test results to Datadog. Currently we have a big suite of JMX test scripts and use Datadog Backend Listener to send live results to Datadog.
I am pushing for DSL as the way forward for easier CI/CD integration and would like to send the pipeline test result to Datdog.

**Comment by rabelenda** [comment]
Hello, this sounds cool! Thank you for requesting the feature.

Can you give some simple insights of what are the main attributes you set/require in backend listener?

Would something like this be enough, or would you require more settings?:

```java
datadogListener(datadogToken)
```

**Comment by uddirulz** [comment]
Hi,

Thanks for your reply.

Generally the API_KEY is used, but worth getting the settings available in
the actual GUI datadog backend listener plugin itself. It will give the
capability to play around with the settings for sending data.

Thanks,
Uddipan

**Comment by uddirulz** [comment]
Hi,
Any updates on this?

**Comment by rabelenda** [comment]
Hello, 

We have just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v1.13) that includes `datadogListener`.  

Please try it and let us know.

**Comment by uddirulz** [comment]
Hi,

This is wonderful news! Let me try this out.

Thanks & Regards,
Uddipan

**Comment by rabelenda** [comment]
Hello, have you had a chance to try it? Do you think we can close this issue?

**Comment by uddirulz** [comment]
Hi,

Yes I tried. Data is populating in DD. However custom tags are not getting
associated to the results as logs.

**Comment by rabelenda** [comment]
Can you provide an example screenshot on how you usually set this in DataDog plugin in JMeter GUI (or resulting JMX file) and what you get in DataDog Dashboard, to help me understand what is missing and try to reproduce?

**Comment by uddirulz** [comment]
Hi,

Pls refer to this issue -
https://github.com/DataDog/jmeter-datadog-backend-listener/issues/40

Example - If I set any customTags=env:${__P(envType,inc)}, that passes to
the metrics but not the logs. As a result I cant filter based on the tags
for logs. Inspected the code, it seems the tags are not being attached to
the logs. Had to clone the pipeline and add processors as suggested in the
issue.

If you can reproduce I think it's better if you can change your code to
associate the custom tags for the logs as well, and this plugin can then be
ahead of the actual GUI plugin(?)

Thanks & Regards,
Uddipan

**Comment by rabelenda** [comment]
Closing this issue. If provided solutions are still not enough you can re open this issue.
