### ISSUE TITLE
Integration with elasticsearch to save results

### ISSUE THREAD

**Issue by amitoverflow-ui** [abstracta/jmeter-java-dsl#21]
Feature request.

Possibility to save results to elasticsearch.

Plugin - https://github.com/delirius325/jmeter-elasticsearch-backend-listener could be used.

**Comment by rabelenda** [comment]
Sure, that looks interesting. Thank you for requesting this.

We will consider it for an upcoming release. 

Stay tuned :-).

**Comment by rabelenda** [comment]
We have just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.20) with requested feature. Check the [new user guide section](https://abstracta.github.io/jmeter-java-dsl/guide/#elasticsearch) for details.

**Comment by amitoverflow-ui** [comment]
Thanks a lot for implementing it quickly.
