### ISSUE TITLE
Confusing copy: 'Here is a sample project in case you want to start one from scratch.'

### ISSUE THREAD

**Issue by pjcalvo** [abstracta/jmeter-java-dsl#213]
I feel confused by copy in the docs. In the readme.md I can see:
```
Here is a sample project in case you want to start one from scratch.
```

But I feel the sample project is meant to help me NOT start one from scratch.  So this will make more sense:
```
Here is a sample project in case you don't want to start one from scratch.
```

If you agree with this change I will be happy to open a PR for .net and java docs.

**Comment by rabelenda** [comment]
Hi, thank you for noting this.

Now that you mention it I understand it might be confusing. 

The idea in general is that you don't even create a project and just reuse existing production project to keep tests and production code aligned and running in same pipeline. That is why in that sense, is starting a new project "from scratch".

What do you think of something like this?: "Here is a bootstrap sample project that you may use as starting point"

**Comment by pjcalvo** [comment]
Hi Roger,

Yeah I guess the idea is more accurate but I don't like the redundancy of "`bootstrap` `example project` and  `starting point`"... Also in this case it should be `example` instead of `sample`.

What about:

`Take|Consider|Use this baseline project as a starting point.` ...

**Comment by rabelenda** [comment]
I just updated readme and user guide with similar reference.

Regards
