### ISSUE TITLE
2 issues with running perf test on Azure

### ISSUE THREAD

**Issue by mikeliucc** [abstracta/jmeter-java-dsl#217]
I've been playing with perf. test on Azure (Azure Load Testing). Lots of fun and possibilities.

Currently, however, I'm facing 2 issues:
1. `splitCsvsBetweenEngines()`: things get weird when I enable the "split CSV evenly between Test engines" option. It turns out the only the first engine is getting the CSV test data properly. The other engines are not (at least it doesn't look that way) - and HTTP requests fired from these engines have the `${...}` string in the URL instead of the CSV test data. Any idea?
2. JSR223 support. Rodger, you might have mentioned about this in one of our prior conversations. But I can't find that thread right now. If I have any JSR223 Post Processor, then the generated JMX would have reference to `us.abstracta.jmeter.javadsl.core.postprocessors.DslJsr223PostProcessor`. This is causing my test to fail when runnning on Azure. Any chance this can be fixed, somehow?

Thanks!!

Mike

**Comment by rabelenda** [comment]
Hello Mike,

1. That behavior sounds weird. I will ask the Azure Team to see if they might know the reason for such behavior. I guess you have already verified that the flag looks set in Azure load test , and that running a similar test with manual setup works fine.

3. Have you checked [this user guide section](https://abstracta.github.io/jmeter-java-dsl/guide/#lambdas). In future release of jmeter-java-dsl it will not be necessary to add jmeter-java-dsl jar as an asset (the azure engine will automatically add it).

**Comment by rabelenda** [comment]
If you could provide some sample (removing any specific or sensitive info) of your code we might be able to help you find a solution.

**Comment by rabelenda** [comment]
Hello @mikeliucc , the Azure team asked told me

"Can we check for the test run ID for us to debug? If they don’t want to share it publicly they can create an issue on https://developercommunity.microsoft.com/loadtesting and share it privately with us."

Let me know if I can help you reaching them or make things faster.

**Comment by rabelenda** [comment]
@mikeliucc have you had any news on this?

**Comment by rabelenda** [comment]
@mikeliucc have you had any news? Otherwise I will close this issue.
