### ISSUE TITLE
Loading Resources with CSVDataSet and TestResource

### ISSUE THREAD

**Issue by imk-github** [abstracta/jmeter-java-dsl#218]
**Problem Description:**

I am using the following code to load Entryserver-IP's from a CSV File. The File is residing in the src/test/resources directory. 

    public DslCsvDataSet entryservers() {
        return csvDataSet(testResource("entryservers.csv"))
                .variableNames(ENTRYSERVER_VAR)
                .ignoreFirstLine(false)
                .delimiter(",")
                .stopThreadOnEOF(false)
                .sharedIn(DslCsvDataSet.Sharing.THREAD_GROUP);
    }

This code works well, as long as it is executed in IntelliJ withou packing it into a JAR.
 
But when executed in JAR (with openJDK 17.0.7), the following way:

`$ java  -cp classes:target/dependencies-3party/*:target/portal-lasttest-jmeter-backend-2.x-SNAPSHOT-tests.jar       ch.ejpd.idmportal.loadtest.backend.WSTrustSectokenTest`

I will get the following exception

`JUnit Jupiter:WSTrustSectokenTest:loadtestWsTrust()
    MethodSource [className = 'ch.ejpd.idmportal.loadtest.backend.WSTrustSectokenTest', methodName = 'loadtestWsTrust', methodParameterTypes = '']
    => java.lang.IllegalArgumentException: URI is not hierarchical
       java.base/java.io.File.<init>(File.java:420)
       us.abstracta.jmeter.javadsl.util.TestResource.file(TestResource.java:46)
       us.abstracta.jmeter.javadsl.util.TestResource.filePath(TestResource.java:62)
       us.abstracta.jmeter.javadsl.JmeterDsl.csvDataSet(JmeterDsl.java:1666)`

entryservers.csv is in Jarfile (Root) 

**Suspection:**
From my point of view: The Problem is this code in the class TestResource:

class JMeterDsl:

    public static DslCsvDataSet csvDataSet(TestResource resource) {
        return new DslCsvDataSet(resource.filePath());
    }

and then, in class TestResource, this.file() is called:

    public String filePath() {
        return this.file().getPath();
    }

this.file() will do the following:

    public File file() {
        try {
            return new File(this.resource.toURI());
        } catch (URISyntaxException var2) {
            throw new RuntimeException(var2);
        }
    }

**new File(..) will not work when you use JAR-Ressources and leads to the Excpetion mentioned above**

**Comment by rabelenda** [comment]
Hello, thank you for reporting this!

Have you considered using maven to run the tests?

Any particular reason to package tests as jars and run from command line instead of using maven or gradle to run them?

One alternative might be in your java code to copy the test resources (using for example the rawContents) to temporary files and then use those temp files paths as parameters to `csvDataSet`. We don't do that as default in jmeter DSL since in most scenarios (running with maven, gradle, etc) it is not needed.

What do you think?

**Comment by imk-github** [comment]
Yes, it is a sort of special case but in our loadtest-scenarios it is quite common: We have to pack the Code into a test-jar and the we deploy it into a docker container. This container will be deployed to a Kubernetes-Cluster wich will be used as a scalable loadtest-base. I have engineered a solutien which replaces the file() method in TestResource. Consider the following subclass of TestResource. It copies the resourcefile on-the-fly into a temporary file wich will be returned to the caller. Fine for me at the moment.

```
package ch.ejpd.idmportal.loadtest.backend;

import us.abstracta.jmeter.javadsl.util.TestResource;

// imports...

public class EjpdTestResource extends TestResource {

    private String resourcePath;
    private File internalResourceFile;

    public EjpdTestResource(String resourcePath) {
        super(resourcePath);
        this.resourcePath = resourcePath;
    }

    /** Overwrite file() in order not to use the java.io.File class, because this won't word with resources in JAR-Files */
    public File file() {

        if (internalResourceFile != null) {
            return internalResourceFile;
        }
        ClassLoader loader = (ClassLoader) Optional.ofNullable(Thread.currentThread().getContextClassLoader()).orElse(TestResource.class.getClassLoader());
        try (InputStream stream = loader.getResourceAsStream(this.resourcePath)) {
            File targetFile = File.createTempFile(UUID.randomUUID().toString(), null);
            targetFile.deleteOnExit();

            java.nio.file.Files.copy(
                    Objects.requireNonNull(stream),
                    targetFile.toPath(),
                    StandardCopyOption.REPLACE_EXISTING);
            return targetFile;
        } catch (IOException ex) {
            throw new RuntimeException("Could not read stream %s".formatted(this.resourcePath), ex);
        }
    }
}
```
