### ISSUE TITLE
jmdsl.jar recorder is making an external call to download the Selenium Manager

### ISSUE THREAD

**Issue by ImtheOneNow** [abstracta/jmeter-java-dsl#221]
Due to our corporate policy, we are not allowed to download nor have an application make external calls to download applications from the internet.  This is a security risk.  If you can suggest another method to include and use the chrome driver executable via the command line that would be great.  Otherwise, it would great to give users of this jar an option to chose whether to download the manager or not.  

Thank you

**Comment by rabelenda** [comment]
Hello, thank you for reporting this!

What operating system are you running in (windows, mac, linux)?

What is the actual url you see the DSL is trying to download?

As you may have noticed we use Selenium to start the recording browser, and selenium itself is the one doing such requests.

Have you tried running with `-Dwebdriver.chrome.driver=<pathToChromeDriverExec>` java system property?

Regards

**Comment by ImtheOneNow** [comment]
Hello,

The OS is Windows. Thank you for clarifying that it's selenium making the external call.  I have not tried running the command your referenced.  Full disclosure here, I'm new to JMeter DSL and I'm more on the Performance Engineering side of things versus being more involved with day to day application development.  Having said this, I may have missed what I need to do.  Furthermore,  I did some research prior to opening the issue and what I saw was that I had to set the path while in the IDE.  I will give your suggestion a try.

**Comment by ImtheOneNow** [comment]
Hello,
Have you tried running with -Dwebdriver.chrome.driver=<pathToChromeDriverExec> java system property in it worked.
Thanks

**Comment by ImtheOneNow** [comment]
I've tried running with -Dwebdriver.chrome.driver=<pathToChromeDriverExec> java system property and it worked

**Comment by rabelenda** [comment]
Great! Thank you for letting us know.
