### ISSUE TITLE
Need help with an exception "Thread 20" java.lang.NoClassDefFoundError: org/apache/commons/codec/Base 64

### ISSUE THREAD

**Issue by ImtheOneNow** [abstracta/jmeter-java-dsl#224]
Hello again :-)

I tried to run the Recorder from within IntelliJ's console (PowerShell) and via cmd and received a "Thread 20" java.lang.NoClassDefFoundError: org/apache/commons/codec/Base 64 exception after the Chrome browser appeared.  I checked my .M2 folder and the jar is there.  I tried setting my ClassPath so that it would point to the commons-codec.jar. I also tried to add it as a dependency in the pom.xml also.  But I continued to receive the same error.  I'm sure I'm doing something wrong but I'm not sure what.

Thank you

**Comment by ImtheOneNow** [comment]
Resolved the issue by running java -cp jmdsl.jar:commons-codec.jar -jar jmdsl.jar

**Comment by rabelenda** [comment]
Can you please provide the full stack trace of the issue so we can better identify when is the dependency actually required? The dependency requirement might depend on the particularities of application requests you are recording.

Regards
