### ISSUE TITLE
Support both a number of iterations and Duration

### ISSUE THREAD

**Issue by Melanie-RK** [abstracta/jmeter-java-dsl#242]
In JMeter I can set both a number of iterations and specify a thread lifetime (Duration) for a ThreadGroup, however, the DSL currently does not support this.

Use case:

I specify the thread lifetime to make sure a test does not exceed a certain duration

Screenshot:
![issue_screenshot](https://github.com/abstracta/jmeter-java-dsl/assets/98179508/cc36f118-415a-4d73-a151-01620a9552c6)

**Comment by rabelenda** [comment]
Thank you for asking for this!

This is an interesting use case. Anyone else with the same need?

We may implement something like:

```java
threadGroup()
 .rampTo(1, Duration.ofSeconds(1))
 .holdIterating(30)
 .upTo(Duration.ofMinutes(200))
```

Any other ideas or comments?

**Comment by Melanie-RK** [comment]
That looks good to me, very easy to see at a glance what it does

**Comment by rabelenda** [comment]
This has been added on [latest release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v1.24)
