### ISSUE TITLE
Add support for lambdas in azure

### ISSUE THREAD

**Issue by Arif-Bipu** [abstracta/jmeter-java-dsl#251]
My team will be using azure load testing and would like the ability to use lambdas in azure

**Comment by rabelenda** [comment]
I forgot to answer this issue, but we have already discussed about it in Discord. Thank you very much to bring it here.

**Comment by rabelenda** [comment]
This was already released in [1.19](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v1.19). I will update some sections in user guide which still need some fixes. Sorry for the confusion.

**Comment by Arif-Bipu** [comment]
hey @rabelenda just to be clear, the uploaded artifacts, will it work with lambda usage? that was the original question i had but wasnt sure

**Comment by rabelenda** [comment]
Yes, it should. You can check [this user guide section](https://abstracta.github.io/jmeter-java-dsl/guide/#lambdas) for more details
