### ISSUE TITLE
Add support to Stepping Thread Group

### ISSUE THREAD

**Issue by yioyoiyioys222** [abstracta/jmeter-java-dsl#252]

**Comment by yioyoiyioys222** [comment]
Screenshot:
![image](https://github.com/abstracta/jmeter-java-dsl/assets/50391716/f6ce9e8d-4dd1-462e-9349-0c0adc2f0b9d)

**Comment by rabelenda** [comment]
Hello @yioyoiyioys222. Thanks for asking about this.

Is there any particular scenario that you would like the DSL to support?

You can achieve the same as stepping thread group with existing api, with a little of java code. 

For example, to create a thread group that creates 100 threads with 10 threads every 10 seconds using ramp ups of 2 seconds with an initial delay of 5 seconds, holds final load for 30 seconds, and ramp down all threads in 5 seconds you could do something like this:

```java
DslDefaultThreadGroup tg = threadGroup()
        .holdFor(Duration.ofSeconds(5));
    for (int i=0; i < 100/10; i++) {
      tg.rampToAndHold(10, Duration.ofSeconds(2), Duration.ofSeconds(10));
    }
    tg.holdFor(Duration.ofSeconds(30 - 10));
    tg.rampTo(0, Duration.ofSeconds(5));

    testPlan(
        tg.children(
            httpSampler("http://example.com")
        )
    ).run();
```

**Comment by yioyoiyioys222** [comment]
Okay, thank you.
