### ISSUE TITLE
getting socket connection closed when using rpsThreadGroup

### ISSUE THREAD

**Issue by mhkhan4** [abstracta/jmeter-java-dsl#262]
When I use: `threadGroup(50, Duration.ofSeconds(10)`

I see no issues it works fine, 100% of the time.

But when I use **rpsThreadGroup**, even though there are so much less throughput gets generated most of the time we see socket connection closed error:

```
rpsThreadGroup()
     .maxThreads(50)
     .rampToAndHold(10, Duration.ofSeconds(5), Duration.ofSeconds(10))
     .children( httpSampler("http://my.service") ) 
```

I'm seeing this error in the jtl file:
`1711817935380,773,[GET] /alerts,Non HTTP response code: java.net.SocketException,Non HTTP response message: Socket closed,cba-alerts [AtomicTests]-ThreadStarter 1-6,text,false,,3172,0,7,7,
[http://myServer/v1/alerts,0,0,0](http://myserv/v1/alerts,0,0,0)`

Tried increasing the time for connectionTimeOut configuration, but it didn't solve the issue

**Comment by rabelenda** [comment]
Hello, have you tried it?

If I don't get an answer I will consider this issue as closed.
