### ISSUE TITLE
Want to use in python projects

### ISSUE THREAD

**Issue by yioyoiyioys222** [abstracta/jmeter-java-dsl#267]
Hi

Nice, project, thanks for doing that.
do you plan to add support for python??

**Comment by rabelenda** [comment]
Hello, there already exists [pymeter](https://github.com/eldaduzman/pymeter) implemented by @eldaduzman. Have you checked that? it is referenced in this repo readme as well.

**Comment by yioyoiyioys222** [comment]
Pymeter was last updated five months ago

**Comment by eldaduzman** [comment]
@yioyoiyioys222 right, Ive been waiting for some user input for a while.

I'll look at the issues you've opened and I'll see which ones I can develop.

Feel free to send pull request too 😊
