### ISSUE TITLE
Jmeter Master e Slave

### ISSUE THREAD

**Issue by reinaldorossetti** [abstracta/jmeter-java-dsl#28]
As I work with master and slave on jmeter dsl, I didn't see anything in the documentation, I needs to do a high load of data in several machines???

**Comment by reinaldorossetti** [comment]
Sorry, I didn't see that you implemented the feature, thanks, I will test it here.

**Comment by reinaldorossetti** [comment]
Do you have any examples using git actions? The host changes all the time, the machines can be different every time you run it.

**Comment by rabelenda** [comment]
What are you trying to achieve? create the agents/testing infra and destroy it in each github action run? If that is the case I don't have any examples. If that is the case and you are using AWS to spin up the instances, you can assign static ips to the instances, or with aws cli find the IP addresses of created instances and parameterize the test accordingly (eg: storing IPS list in an environment variable and using `Sytem.getenv` to retrieve it in jmeter DSL test).
