### ISSUE TITLE
While loading .jmx file existing file and run it from Jmeter DSL iam gettting error CannotResolveClassException: org.apache.jmeter.protocol.system.SystemSampler

### ISSUE THREAD

**Issue by Farahala** [abstracta/jmeter-java-dsl#283]
- While loading .jmx file already existing file and run it from Jmeter DSL  as TestPlanStats stats = DslTestPlan.fromJmx("file.jmx").run(); 
- iam gettting error CannotResolveClassException: org.apache.jmeter.protocol.system.SystemSampler

1. The .jmx file contain OS sampler that is Curl

    <SystemSampler guiclass="SystemSamplerGui" testclass="SystemSampler">
          <stringProp name="SystemSampler.command">curl</stringProp>

- I need to know how i can run  .jmx file that contain the OS sampler using jmeter DSL  as i always get CannotResolveClassException: org.apache.jmeter.protocol.system.SystemSampler.

**Comment by rabelenda** [comment]
Hello,

Have you tried including this dependency in your project?:

```xml
<dependency>
    <groupId>org.apache.jmeter</groupId>
    <artifactId>ApacheJMeter_native</artifactId>
    <version>5.5</version>
</dependency>
```

**Comment by Farahala** [comment]
> ```
> <dependency>
>     <groupId>org.apache.jmeter</groupId>
>     <artifactId>ApacheJMeter_native</artifactId>
>     <version>5.5</version>
> </dependency>
> ```
 Yes i tried to added but i get the same issue 
Cause:
CannotResolveClassException: org.apache.jmeter.protocol.system.SystemSampler
Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree[12]/hashTree[8]/SystemSampler
line number         : 16267
version             : 5.5
-------------------------------

**Comment by rabelenda** [comment]
If you are using an IDE to run the tests, have you verified that the dependency is properly refreshed after adding it to pom.xml? I just tried a simple scenario and adding the dependency to pom and refreshing ide works. I also tried without the IDE (mvn clean test) and works as well.

**Comment by Farahala** [comment]
yes , I tried again and it is works now .
Thanks
