### ISSUE TITLE
is there is any Build in function in jmeterDSL to check the 90% Percentile .and the 95% Percentile

### ISSUE THREAD

**Issue by Farahala** [abstracta/jmeter-java-dsl#284]
is there is any Build in function to check the 90% and the 95% like the one that Jmeter dsl have for 99% "sampleTimePercentile99()"

**Comment by Farahala** [comment]
Thanks , and is there is a build in function also to  get the Average response time ?

**Comment by rabelenda** [comment]
Yes, you can check available methods with any IDE.
