### ISSUE TITLE
Jmeter logging 

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#34]
Is there the way how to write JMeter log to the console/stdout?

**Comment by rabelenda** [comment]
Hello, 

sure! Please check last tip in [this section of user guide](https://abstracta.github.io/jmeter-java-dsl/guide/#simple-http-test-plan).

**Comment by rabelenda** [comment]
In particular you can set jmeter logger to INFO by changing this line: `<Logger name="org.apache.jmeter" level="INFO"/>`

**Comment by kirillyu** [comment]
I see only jtl logs in rhis example. Not console logging and no jmeter errors. So if I got the exception in JSR223 groovy code when used this example should I see the log in output? And i don't see the line `<Logger name="org.apache.jmeter" level="INFO"/>` in any code examples

**Comment by rabelenda** [comment]
The section includes a reference to [this log4j2.xml file](https://github.com/abstracta/jmeter-java-dsl/blob/master/jmeter-java-dsl/src/test/resources/log4j2.xml). The file contains this line `<Logger name="org.apache.jmeter" level="WARN"/>`. You may copy the file and change that line with the previously provided one to get all jmeter logs.

**Comment by kirillyu** [comment]
Should I create this file in my project? If the default was WARN level - I have not seen warnings of this type

**Comment by rabelenda** [comment]
Yes, to control the JMeter logging, copy the file, and tune it (for instance: remove other defined loggers in file, and change the jmeter log level).

Regarding the warn level, try changing to INFO and let me know. In general no warnings are generated, but if you see some particular log is not being logged when it should we can review. In general configuring log4j2.xml properly should be enough.

**Comment by kirillyu** [comment]
Hm... It looks like it works. Thank you, if you have any questions - I'll write.
