### ISSUE TITLE
HTTP request defaults

### ISSUE THREAD

**Issue by EugeneKazakov** [abstracta/jmeter-java-dsl#36]
Hi,

Due to requests most often are going to the same server we would like to request support of https://jmeter.apache.org/usermanual/component_reference.html#HTTP_Request_Defaults
It would significantly simplify the scripts automation
The most used parameters for us are: protocol, server name/IP, port, implementation, content-encoding, retrieve embedded resources.

Thank you!

**Comment by rabelenda** [comment]
Hello,

Thank you for asking this, it has been in our backlog for a while but have not prioritized it yet.

Do you think that protocol, server name/IP and port are actually needed to be supported in a separate test element as is in JMeter? Do you see any significant advantage (for your use case) on having a separate method/builder for specifying them, than just using  a java variable and string concatenations? Eg:

This:

```java
TestPlanStats stats = testPlan(
    threadGroup(2, 10,
        httpDefaults().protocol("http").host("my.service").port(8080)
        httpSampler("/users"),
        httpSampler("/status")
    )
).run();
```

Over this:

```java
String baseUrl = "http://my.service:8080";
TestPlanStats stats = testPlan(
    threadGroup(2, 10,
        httpSampler(baseUrl + "/users"),
        httpSampler(baseUrl + "/status")
    )
).run();
```

If you have an interesting case where the former would make sense, can you share it?

About the implementation option: do you usually use an implementation other than the httpClient? Can you describe when do you use the Java implementation instead and why?

I see a clear benefit on having content-encoding and embedded resources in some general settings. 

Until we settle on final design and make a release, in the meantime and as a work around, you could create a method that builds the sampler with pre defined settings and just reuse it. Eg:

```java
public DslHttpSampler buildHttpSampler(String path) {
  return httpSampler("http://my.service:8080" + path)
        .downloadEmbeddedResources()
}

TestPlanStats stats = testPlan(
    threadGroup(2, 10,
        buildHttpSampler("/users"),
        buildHttpSampler("/status")
    )
).run();
```

Thank you again, and I hope to hear from you soon with additional info that helps us design the DSL as simple as possible but also covering what you and in general de community need.

Regards

**Comment by rabelenda** [comment]
Hello,

Have you had a chance to look into above comments and questions?

Regards

**Comment by EugeneKazakov** [comment]
Hi,
`do you usually use an implementation other than the httpClient? Can you describe when do you use the Java implementation instead and why?`
yes, we have seen an article that says that Java client is more performing than HTTPClient4
but we also can set it over jmeter.properties file
BTW, what is the way that JMeter DSL  managing/changing jmeter.properties?

`If you have an interesting case where the former would make sense, can you share it?`
well, simply 
`threadGroup(2, 10,
        httpSampler(baseUrl + "/users"),
        httpSampler(baseUrl + "/status"),
        httpSampler(baseUrl + "/1"),
        httpSampler(baseUrl + "/2"),
        httpSampler(baseUrl + "/3"),
        httpSampler(baseUrl + "/4"),
        httpSampler(baseUrl + "/5"),
        httpSampler(baseUrl + "/6"),
        httpSampler(baseUrl + "/n")
    )`

**Comment by kirillyu** [comment]
@EugeneKazakov you can you use java for addition features like this. 
```String baseUrl = "https://yourwebsite.com"
TestPlan(
threadGroup(2, 10,
        httpSampler(baseUrl + "/users"),
        httpSampler(baseUrl + "/status"),
        httpSampler(baseUrl + "/1"),
        httpSampler(baseUrl + "/2"),
        httpSampler(baseUrl + "/3"),
        httpSampler(baseUrl + "/4"),
        httpSampler(baseUrl + "/5"),
        httpSampler(baseUrl + "/6"),
        httpSampler(baseUrl + "/n")
    )
)```

**Comment by rabelenda** [comment]
Hello,

Thank you for further clarifying this!

Can you share the post that you mention? In some scenarios might be faster, but in general is preferable to just use HTTPClient4, mainly due to connections reuse.

For setting jmeter properties you can use `System.setProperty("name", "value")` before running the testplan. 
We might in the future implement some abstraction over it, but for the time being setting system properties is simple enough. This question has been answered in another issue, we will add a note in documentation to make it more explicit. Thank you for bringing this to our attention.

Regards

**Comment by EugeneKazakov** [comment]
@rabelenda it's a bit in Russian https://polarnik.github.io/Apache.JMeter.Benchmark.NG/#42
:)

**Comment by EugeneKazakov** [comment]
@kirillyu do you enjoy typing `baseUrl` all the time?

**Comment by kirillyu** [comment]
It's feature to use java environment. It happens before the test starts and jmeter easily uses it. So, yes I enjoy))

It should be noted that I have only been using DSL for a few weeks and have not yet run extensive tests.  But I studied everything for a very long time and carefully.

But in general, this is not just an increase in productivity.  JavaClient, for example, works differently with connections, certificates and cryptography.  It lacks some of the functionality and therefore is lighter in resource consumption.  I am using HTTPClient4 - it works more reliably

@EugeneKazakov английский это боль :D

**Comment by EugeneKazakov** [comment]
I should say that having a default config is a common practice

rest-assured has it https://github.com/rest-assured/rest-assured/blob/2389456a4f313b733c2c1c462f12686cd0e81f8f/examples/rest-assured-itest-java/src/test/java/io/restassured/itest/java/URLITest.java#L48

gatling has it https://gatling.io/docs/gatling/reference/current/http/protocol/#base-url

Jmeter has it in GUI

and so on

**Comment by rabelenda** [comment]
> @rabelenda it's a bit in Russian https://polarnik.github.io/Apache.JMeter.Benchmark.NG/#42 :)

Thank you, I will use a translation tool 😄 .

> @EugeneKazakov английский это боль :D

I used the translator here to get it 😆. I am not a native speaker either, but english is the most spread secondary language and furthermore in programming community.

I think we have enough reasons to implement a baseUrl common setting, and with that other elements that you mention.

Thank you very much @EugeneKazakov

**Comment by rabelenda** [comment]
We just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.39) which includes [httpDefaults](https://abstracta.github.io/jmeter-java-dsl/guide/#http-defaults) method.

**Comment by rabelenda** [comment]
Closing this issue, let us know if you have any comments
