### ISSUE TITLE
HTTP header manager

### ISSUE THREAD

**Issue by EugeneKazakov** [abstracta/jmeter-java-dsl#37]
Hi again)
We would like to have the next functionality covered in the DSL https://jmeter.apache.org/usermanual/component_reference.html#HTTP_Header_Manager
Most requests emulating users usually have the same headers, so having that would simplify scripting.
Thanks!

**Comment by rabelenda** [comment]
Hello,

Have you checked checked [this section of the user guide](https://abstracta.github.io/jmeter-java-dsl/guide/#headers)? Do you see anything that you need and is still not supported in this regard?

Regards

**Comment by EugeneKazakov** [comment]
Yes, my bad, missed that
