### ISSUE TITLE
JDBC Sampler, SetUp and TearDown thread groups

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#38]
I have already started porting my tests to DSL, but I still have difficulty doing it one-to-one. The functionality of these elements is very lacking in order to launch a number of projects through DSL. Much thanks for supporting!

**Comment by rabelenda** [comment]
Hello,

Sure! Thank you for asking for them.

Can you describe the use case where you use JDCB Sampler in most of the scenarios? What are the type of queries you usually use? more inserts/updates or more queries? What are the fields/settings you usually use in sampler and connection config? 

On setup and teardown threadgroups, do you ever use more than 1 thread an 1 iteration, or use duration?

Thank you

**Comment by kirillyu** [comment]
![image](https://user-images.githubusercontent.com/9977326/141177388-fcbe47b1-fa9b-4710-8111-13dce9f9affd.png)
Regarding threads: I most often use these groups with 1 thread, but it happens that I set the loop to infinity. I also expose the error behavior as in the screenshot. Very rarely I put more than one threads.

I use JDBC to generate or prepare test data. At the output, I get a map or csv, which I then use in the test. I use them less often to check the content of data. Configuration on the screenshot. Yellow - frequently used fields.
![image](https://user-images.githubusercontent.com/9977326/141177944-44ef4c22-baa6-4cb2-a0a8-38c6bf46dd93.png)

Next is the sampler itself.
![image](https://user-images.githubusercontent.com/9977326/141178112-b9b48a70-b37c-4f59-ba5c-e41d178fa02c.png)

**Comment by rabelenda** [comment]
Great info, thank you very much!.

Regarding setup & teardown thread groups:

* For what purposes you create a setup thread group with infinit loops? Can you describe the use case?
* Can you describe a scenario where you use more than one thread in setup/teardown thread groups?

Regarding JDBC:

* Do you think is actually needed to have a specific setting for limit resultSet? Maybe if the user wants a limit can just specify it in the query? I think that would be in general a better practice.
* When do you usually change ho resultSet is handled, and why?

Thank you again for providing all this info, and helping in the design of the DSL 🙂 .

Regards

**Comment by kirillyu** [comment]
tearDown and setup threads:

- If I want to be sure that the thread group will complete all requests successfully, I make an endless loop and put Flow Control Action with the "Stop Now: Current Thread Group" parameter at the end of the thread group. And action to be taken after Sample Error is "Continue".
In this example, the main test will not start for me until the verification passes, or the data is generated, or any other process is guaranteed to be successful. This can be necessary for a test and saves time by allowing only good tests to be performed.

- Probably I need to logot for all users in teardown, or create a cash for user by making one request to system in setUp. Something like this. And it's usefull for data generation. If I need to authorize all users before test I can create, for example, LinkedHashMap, put it into the prop and push from each user auth token to it. That's it

JDBC: 

- Oh, I was not accurate. This is not really necessary. And parameter types too.
- Never :D

**Comment by kirillyu** [comment]
Partly closed by [0.33](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.33) release

**Comment by rabelenda** [comment]
We are currently considering a design like following for jdbc elements:

include a jmeter-java-dsl-jdbc module to use it, to group all jdbc builder methods in one class and avoid adding jdbc jmeter dependency when is not needed. Additionally, jdbc is not as commonly used as http for example, so we think having a separate module makes sense in this scenario.

```java
import static us.abstracta.jmeter.javadsl.jdbc.JdbcJmeterDsl.*

jdbcConnectionPool("myDbPool", com.mysql.jdbc.Driver.class, "jdbc:mysql://myhost:3306/my_db")
  .user("myUser")
  .password("myPass")
  .autoCommit(false)
  .maxConnections(50)
  .maxConnectionWait(Duration.ofSeconds(10))
  .transactionIsolationLevel()
  .connectionProperties()

jdbcSampler("myDbPool", "SELECT id, name FROM users WHERE name like ?")
  .vars("USER_ID", "USER_NAME")
  .resultsVar("USER_RESULTS")
  .timeout(Duration.ofSeconds(10))
  
jdbcSampler("myDbPool", "INSERT INTO users(id, name) VALUES (?, ?)")
  .param(1, Types.INTEGER)
  .param("John Doe", Types.VARCHAR)

jdbcSampler("myDbPool", "EXEC update_name(?, ?)")
  .param(1, Types.INTEGER)
  .param("John Doe", Types.VARCHAR, JdbcParamMode.INOUT)
  .vars("USER_NAME")

jdbcSampler("myDbPool").commit()
jdbcSampler("myDbPool").rollback()
jdbcSampler("myDbPool").autoCommit(false)
```

I see that you marked as used the following items in connection pool:
* evictionRunsPeriod: do you usually require to tune this property? Sounds quite low level. When do you usually tune such property?
* autoCommit: In most of the cases I would expect to use autoCommit. In some cases you might need to set it to false to be more performant and commit several queries at once. Do you usually set this to false?
* transactionIsolationLevel: In some scenarios you may need to change the transactionIsolationLevel. This usually is required when having queries contingencies or when performance is important. Do you usually use this? Can you describe in what type of scenarios you use it? because initially I would tend to think that for environment setup or data content checks it would not be required.
* preInitPool: I tend to think that this should be true in most of the cases. What do you think? Do you see a benefit on having it set to false in some scenarios? When would you use it as false or give the user the option to select either to enable it or not?

Thank you very much for all your requests and help.

Regards

**Comment by kirillyu** [comment]
One question - why this is not the main package?

**Comment by rabelenda** [comment]
Hello,

Main part of the answer is here:

> include a jmeter-java-dsl-jdbc module to use it, to group all jdbc builder methods in one class and avoid adding jdbc jmeter dependency when is not needed. Additionally, jdbc is not as commonly used as http for example, so we think having a separate module makes sense in this scenario.

The jdbc part of jmeter is in a separate jar/dependency, and on top of previous points, having a separate module would avoid adding more methods to existing JmeterDsl (easing it's usage). In general I think that except from http protocol (which is the most used one, and most of the tools consider it a core feature), the rest of protocols makes sense to have a separate module. In this case, as many applications use JDBC, is not as clear as in other protocol cases, but I think that JDBC is not a thing for most of projects either (maybe less that 30%, just guessing from what I have seen, but this highly depends on the profile of apps you are testing).

Regards

**Comment by rabelenda** [comment]
We have just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.38) which includes `jdbcConnectionPool` and `jdbcSampler` elements. Check the [new user guide section](https://abstracta.github.io/jmeter-java-dsl/guide/#jdbc-and-databases-interactions).

**Comment by rabelenda** [comment]
Closing this since seem that main requirements have been covered in past releases. Feel free to re open if you see anything is missing in this regard.
