### ISSUE TITLE
YAML scripting feature 

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#40]
Many people use jmeter because there is no code there. Simple QA can understand this. And this is the reason for its popularity and large community. Perhaps in the future it is worth thinking about expanding the audience by eliminating the code layer in Java or Kotlin. And use YAML interpretation. As done in taurus https://gettaurus.org/docs/JMeter/#Requests 
What you think?

**Comment by rabelenda** [comment]
Hello,

This is a very interesting matter/discussion and idea.

What do you think would be the main differentiators for the DSL over taurus in such scenario?

I can come up with no need for Python env. Another may be potentially/eventually more complete coverage of jmeter features, but in this regard maybe makes sense just to try contribute to taurus and see if taurus team is willing to include more coverage. Another might be more direct mapping between jmeter model and yaml, than taurus (which is more of a general purpose tool and not particularly focused in jmeter).

For the time being, I don't think this is a big differentiator, and in general, for such scenarios, would recommend just using taurus. But let's keep the issue and discussion open, to see your and others point of view, and maybe in the future we can prioritize it.

Regards, and thank you very much for bringing new ideas and things for discussion and thought.

**Comment by kirillyu** [comment]
The Taurus has a number of pros and cons. DSL is clearly not a plus. I think you have the only project that suits this role.
I could implement YAML for my scenario, but the implementation would be weak. In order to add it to the core of the DSL, you need to seriously think about it. But the model itself fits well with the example with RPSThreadGroup, which we discussed earlier.

**Comment by kirillyu** [comment]
I will add that for me this feature would probably be useless and would reduce flexibility.  But for a typical QA or for people who do not understand java, it sounds good.

**Comment by vlsi** [comment]
I do not think yaml would really solve the problem: you have to write code, you have zero type safety, and no autocomplete 🤷‍♂️

**Comment by kirillyu** [comment]
Maybe close it? What you think @rabelenda?

**Comment by rabelenda** [comment]
Yes, let's close it. 

I decided to keep it open in case some other points are raised, but so far, with current evaluation this doesn't seem like something we should be tackling soon. 

If anyone has interest in this or has more points please add your comments in this ticket and we may re open it.
