### ISSUE TITLE
Groovy code debug

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#41]
Any ideas how to effective and fast debug groovy code? Is it possible to run it without the test itself, but with some kind of context?

**Comment by rabelenda** [comment]
Hello,

I don't have right now an answer to this, aside potentially to use the lambdas alternative (but they have the problem of not working with Blazemeter or being properly exported to JMX). I will review and let you know, but yes, I guess you could test them with auxiliary groovy with proper setup (creating JMeter variables instance, and other potentially needed parameters/context) script and using IDEs groovy debugger. I don't think is possible to debug JMeter groovy script code right into the context of a JMeter test plan with Java debugger, since for java is just a string (and can't put a breakpoint). One idea to explore might be to put some java code in groovy that you can put a break on (maybe an object with a method in java with the breakpoint) and then debug it, but that would require modifying the groovy code and would potentially be not portable to JMX or Blazemeter again.

As a lame workaround you can always use log statements.

I will take a further look into it and let you know. 

Regards.

**Comment by kirillyu** [comment]
Much thaks!

**Comment by rabelenda** [comment]
Hello, 

Here are some options that I tried:

1. Setting a breakpoint in GroovyScriptEngineImpl when it reaches the line containing `scriptObject.run()`, trigger a debug on your ide and then step into the breakpoint and then step over one line at a time. The main problem with this is that IDE doesn't show you the usual indicator in groovy script where the execution is currently positioned. Eg:
 
    ![image](https://user-images.githubusercontent.com/3179183/141364101-fd4903f1-87f8-4ac1-a82a-9fac498a4971.png)

    Is a debug session of this groovy script:

    ```groovy
    def counter_name = 'MY_COUNTER'
    def counter = vars.getObject(counter_name)
    vars.putObject(counter_name, counter?:0 + 1)
    ```

    In debugger screenshot you can see the status of script variables, and you can even explore binding.variables and see 
    variables provided to the groovy script by jmeter. Additionally you see in the image that script is currently at line 3 (run:3).

2. You can add a call in groovy script to java code and put a break point in java code. For example:

    ```java
    import static us.abstracta.jmeter.javadsl.JmeterDsl.jsr223Sampler;
    import static us.abstracta.jmeter.javadsl.JmeterDsl.testPlan;
    import static us.abstracta.jmeter.javadsl.JmeterDsl.threadGroup;

    import javax.script.SimpleBindings;
    import org.junit.jupiter.api.Test;
    import org.slf4j.Logger;
    import org.slf4j.LoggerFactory;

    public class PerformanceTest {

      private static final Logger LOG = LoggerFactory.getLogger(PerformanceTest.class);

      public static void breakpoint(SimpleBindings scriptVars) {
        LOG.debug("Reached breakpoint!");
      }

      @Test
      public void shouldWhen() throws Exception {
        testPlan(
            threadGroup(1, 1,
                jsr223Sampler("def counter_name = 'MY_COUNTER'\n"
                    + "def counter = vars.getObject(counter_name)\n"
                    + "PerformanceTest.breakpoint(binding.variables)\n"
                    + "vars.putObject(counter_name, counter?:0 + 1)")
            )
        ).run();
      }

    }
    ```

    If you put a breakpoint in the `LOG.debug` statement, you get to view all variables in bindings, which contain jmeter variables, jmeter context, etc. Additionally when you reach the breakpoint you can navigate upper in the callstack and see debug info for the groovy script itself, for example:

    ![image](https://user-images.githubusercontent.com/3179183/141362562-1845673d-c67e-45a3-a708-01d99b4ee5c9.png)

    NOTE: use fully qualified name of the class containing the breakpoint method. In previous example the test class is in default package, so was not needed to add fully qualified name.

    **This, and previous options allow you to debug the element while the JMeter test runs!** The later one might be simpler in some scenarios than looking for the correct line in GroovyScriptEngineImpl where to place the breakpoint, but requires modifying the groovy script.

3. If you have the groovy script in a separate file and want to test the script in isolation (not inside a test run),  you can create a separate groovy script with custom defined binding, debug it and set a break point wherever you want in the original script. Eg:

    ```groovy
    new us.abstracta.jmeter.javadsl.core.engines.JMeterEnvironment().withCloseable {
        def binding = new Binding()
        def shell = new GroovyShell(binding)
        def vars = new org.apache.jmeter.threads.JMeterVariables()
        binding.setProperty('vars', vars) // you might add other bindings if you script uses other variables provided by jmeter
        shell.evaluate(new File('./script.groovy'))
    }
    ```

    This option currently requires this exclusions as well:

    ```xml
    <dependency>
      <groupId>us.abstracta.jmeter</groupId>
      <artifactId>jmeter-java-dsl</artifactId>
      <version>0.30</version>
      <exclusions>
        <exclusion>
          <groupId>xerces</groupId>
          <artifactId>xercesImpl</artifactId>
        </exclusion>
        <exclusion>
          <groupId>xml-apis</groupId>
          <artifactId>xml-apis</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    ```

    This approach takes advantage of full groovy debugger but with no option to debug while inside a test runner.

Let me know which of the provided options fit better your use case, and if they are enough for your needs. Or if you have any other ideas.

Regards

**Comment by kirillyu** [comment]
Wow! The last variant is perfect, will try. Thanks

**Comment by rabelenda** [comment]
From [0.33](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.33) on, the groovy script needs to be adapted due to class renaming:

```groovy
new us.abstracta.jmeter.javadsl.core.engines.JmeterEnvironment().withCloseable {
    def binding = new Binding()
    def shell = new GroovyShell(binding)
    def vars = new org.apache.jmeter.threads.JMeterVariables()
    binding.setProperty('vars', vars) // you might add other bindings if you script uses other variables provided by jmeter
    shell.evaluate(new File('./script.groovy'))
}
```

**Comment by rabelenda** [comment]
From [0.33.1](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.33.1) on, the groovy script needs to be adapted to:

```groovy
def env = new us.abstracta.jmeter.javadsl.core.engines.JmeterEnvironment()
def binding = new Binding()
def shell = new GroovyShell(binding)
def vars = new org.apache.jmeter.threads.JMeterVariables()
binding.setProperty('vars', vars) // you might add other bindings if you script uses other variables provided by jmeter
shell.evaluate(new File('./script.groovy'))
```
