### ISSUE TITLE
Add ability to use custom JavaSamplers

### ISSUE THREAD

**Issue by lodgvideon** [abstracta/jmeter-java-dsl#45]
We use a lot of custom JavaSamplers and Listners in our projects.
I want to be able to use them, without extending all of them in DSL. Is it Posible?
example of usage:

```
Arguments samplerArguments = new Arguments();
        samplerArguments.addArgument("name","value");
        TestPlanStats stats = testPlan(
                threadGroup(2, 10,
                        httpSampler("http://my.service")
                                .post("{\"name\": \"test\"}", MimeTypes.Type.APPLICATION_JSON)

                 ),
                  javaSampler("CustomSampleName", MyCustomJavaSampler.class,samplerArguments)
 
                //this is just to log details of each request stats
                jtlWriter("test" + Instant.now().toString().replace(":", "-") + ".jtl")
        ).run();
```

**Comment by rabelenda** [comment]
Hello,

Yes, currently we don't support such feature, but we can consider it for future release.

Have you considered using jsr223 sampler (listener is not in the DSL either, but could be easily added)? Can you give a glimpse of the type of tasks you perform with such samplers and listeners? It would be very interesting in what scenarios you opt for such elements which require programming programming skills. Have you considered releasing them as plugins? or are they too specific for your specific domain?

Thank you, and regards.

**Comment by lodgvideon** [comment]
Well - 
1) Most of them are custom samplers that work with RabbitMQ and send messages to Rabbit with way, that upstream system does. It works on JSR223 before, but i rewrite them to Pure Java for stability and reusability way.
2) Some custom kinds of Rabbit RPC samplers.
3) Samplers, that implement hardcore buisenessLogic. It was simpler to debug them in Java instead of Groovy.
4) Samplers that receive async events from Websockets example: https://github.com/lodgvideon/perfcon-async-jmeter

Most of last group samples are project-specific.

 Also we use custom  FreeFormArrivalsTG, that emulate chain of events for concrete user behavior and send them to rabbit with specified times.

**Comment by rabelenda** [comment]
Thank you very much for this info, is very useful.

I know see your point, I initially thought that you were asking for Java Request JMeter element support. But from the comment about listeners and the last comment on thread group, it seems that you want to use any custom JMeter component in a generic way and don't having to extend a class or similar, right?
 
That is very interesting, haven't thought about such option, but it sounds quite interesting. Let us come up with a potential design and then further discuss it, but what you propose sounds like a good initial draft.

Thank you

**Comment by lodgvideon** [comment]
Yes - you are right.

**Comment by rabelenda** [comment]
Hello,

Please check [last release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.41) and let us know what you think about the [new DSL module](https://abstracta.github.io/jmeter-java-dsl/guide/#custom-or-yet-not-supported-test-elements). 

Does it fit your needs? Is it what you expected?

Regards

**Comment by adzest** [comment]
Hello,

Does this new DSL module support custom TG, such as SteppingTG? Are there any examples for TG?
It is not so popular, but it could mimic any load model type, based on a huge amount of params it provides:
1) stress:
|       /
|    /
| /
+------
2) spikes
|         ^
|       /   \__
|___/
+--------
3) load/endurance:
|
|    ___________________
|_/         |
+------+-------------
...
and other [graphics](https://www.neotys.com/blog/wp-content/uploads/2020/03/image7.png).

**Comment by lodgvideon** [comment]
> Hello,
> 
> Please check [last release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.41) and let us know what you think about the [new DSL module](https://abstracta.github.io/jmeter-java-dsl/guide/#custom-or-yet-not-supported-test-elements).
> 
> Does it fit your needs? Is it what you expected?
> 
> Regards

Looks great. I think with this api, anyone can customize samplers, without writing new Plugins.

**Comment by rabelenda** [comment]
Hi,

> Does this new DSL module support custom TG, such as SteppingTG? Are there any examples for TG? It is not so popular, but it could mimic any load model type, based on a huge amount of params it provides:

Have you checked [this section](https://abstracta.github.io/jmeter-java-dsl/guide/#thread-ramps-and-holds) of user guide? It sounds like it should be enough for your case, and if you want to do something more similar to stepping, you can even create steps in a loop with such api. Eg:

```java
import static us.abstracta.jmeter.javadsl.JmeterDsl.*;

import java.io.IOException;
import java.time.Duration;
import org.junit.jupiter.api.Test;
import us.abstracta.jmeter.javadsl.core.threadgroups.DslThreadGroup;

public class PerformanceTest {

  @Test
  public void testName() throws IOException {
    testPlan(
        buildSteppingThreadGroup(10, 10, Duration.ofSeconds(2), Duration.ofSeconds(10))
            .children(
                httpSampler("https://myservice.my")
            )
    ).run();
  }

  private DslThreadGroup buildSteppingThreadGroup(int steps, int stepThreads,
      Duration stepRampPeriod, Duration stepDuration) {
    DslThreadGroup ret = threadGroup();
    int threadsCount = 0;
    for (int i = 0; i < steps; i++) {
      threadsCount += stepThreads;
      ret.rampToAndHold(threadsCount, stepRampPeriod, stepDuration);
    }
    return ret;
  }

}
```

About custom thread groups, yes, in theory you could use this module for that, but if you refer to some public plugin or feature, is better you create an issue so we implement something in the DSL and the rest of the community can benefit from it.

> Looks great. I think with this api, anyone can customize samplers, without writing new Plugins.

We are glad that looks good for you. Let us know your experience with it.

Regards

**Comment by adzest** [comment]
Hello,

Yes, perfect as always ;)
Now it is clear to me. Some deviation in names with the Jmeter elements confused a bit but community and questions are growing and time will avoid it, good job!
