### ISSUE TITLE
push Jmeter Properties from java

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#46]
I am trying to pass a property to jmeter from java code.
```        Properties props = System.getProperties();
        props.put("productSetId", productSetIds);
        props.put("productSetId_#",productSetIdsCount);``` 
Doen't work. 
```
JMeterUtils.getProperties()
```
 returns null

So what is true way?

**Comment by rabelenda** [comment]
Hello, 

Is this something you want to set before the test plan executes?

Have you tried with `System.setProperty("name", "value")`?

JMeterUtils will only work within a JmeterEnvironment context. Something like:

```java
try (JmeterEnvironment env = new JmeterEnvironment()) {
  JMeterUtils.setProperty("name", "value")
   testPlan(....).run();
}
```

But that code would currently not work since run method already creates a jmeter environment that conflicts with the encolsing one.

Regards

**Comment by kirillyu** [comment]
Yes I would like to do it before. And it's stange that Ststem.props doesn't work cause:
JemterUtils
```
public static void loadJMeterProperties(String file) {
        Properties p = new Properties(System.getProperties());
        InputStream is = null;
        try {
            File f = new File(file);
            is = new FileInputStream(f);
            p.load(is);
        } catch (IOException e) {
            try {
                is = ClassLoader.getSystemResourceAsStream(
                        "org/apache/jmeter/jmeter.properties"); // $NON-NLS-1$
                if (is == null) {
                    throw new RuntimeException("Could not read JMeter properties file:" + file);
                }
                p.load(is);
            } catch (IOException ex) {
                throw new RuntimeException("Could not read JMeter properties file:" + file);
            }
        } finally {
            JOrphanUtils.closeQuietly(is);
        }
        appProperties = p;
    }
```

The general thing: I need to push not string, but hte object.

**Comment by kirillyu** [comment]
Apparently I need to push the data into the properties file. What you think? How to get it?

**Comment by kirillyu** [comment]
This is probably a more complex question about how JMeter is launched. For example, can I pass launch parameters to it? Within them, can I specify a custom path to the properties file or pass my values ​​directly from the launch parameters?

**Comment by rabelenda** [comment]
Hello, now retesting I am seeing some unexpected behavior:

```
@Test
  public void testPerformance() throws IOException {
    String propName = "MY_PROP";
    System.setProperty(propName, "MY_VAL");
    testPlan(
            threadGroup(1, 1,
                httpSampler(wiremockUri + "/${__P('MY_PROP')}"),
                jsr223Sampler(s -> System.out.println(s.props.getProperty("MY_PROP")))
            )
    ).run();
    wiremockServer.verify(WireMock.getRequestedFor(WireMock.urlEqualTo("/MY_VAL")));
  }
```

This test fails since the property function resolves to 1 instead of the value. This is because system properties are used as "default" values, but internally jmeter function specifies to use 1 as defal. The same test though prints the proper value in jsr223Sampler, because then, when no default value is specified, jmeter props will default to the provided system properties. One workaround for the mean time might be using `${__goorvy(props['MY_PROP'])}` instead of `${__P('MY_PROP')}` or `${__property('MY_PROP')}`.

System.setProperties still doesn't allow to set arbitrary objects though, just strings. One option to set arbitrary objects (for the meantime) is using some jsr223Sampler or jsr223Preprocessor with java code and inject the property there.

About passing launch parameters... what do you mean? like the jmeter properties you pass in properties file and through command line like when -J option is used? Those you should be able to set with System.setProperty, or eventually with JMeterUtils or some other approach we come in the future.

Regarding properties file, the DSL uses some temporal files with potentially "non deterministic" path for properties and general JMeter env settings. We could add something for fixing the path, but would need first understand the specific need, since I tend to think that we should opt for other options in general instead of overwritting jmeter properties in the file.

Yes, I think we can work on being able to use the code I sent earlier (with JmeterEnvironment), and use a singleton instance of the JMeter env (to avoid collisions) or some other similar option. We need to settle on a design for that (singleton for instance might not be good to do resources cleanup).

**Comment by kirillyu** [comment]
My issue now:
I create few JDBC Request from java wich executing in @BeforeEach section. In this section I getting the array list and integer objects wich I wolud like to push into JMeter code. I need to do it before JMeter start because there some test setting, for example host for Influxdb Listenter.

My global question:
Yes, this is also about -J param.  
When the task is to profile a Jmeter test, get a Thread / HeapDump or set up an online monitor. Often it is necessary, for example, to open a JMX port - this is done through the Java parameters, which are specified when starting the jar.
Likewise, similar launch parameters may be needed to parameterize a test. For example, here's my solution: https://github.com/kirillyu/jmeterReports2 readme in Russian, of course, but everything is elementary there. You can see the docker-compose and source of jmx template there.

This is a kind of framework that allows you to run a test indicating which project is currently being loaded, generate a unique name for the launch itself and, by the name of the project, know in advance the kubernetes container that needs to be monitored and data on which to collect. I can pass these parameters from anywhere, for example from CI such as Jenkins or Gitlab. Automation of load tests is extremely popular right now, so simply passing parameters inside is a must.

As a result, with your comments, I could not solve the problem. Maybe I misunderstood something.

**Comment by kirillyu** [comment]
Ou, that's clear - the System.setProperties is the same for "-J". OK, probably I need to understand how to push it from CI :))
There is only question about current issue (push object from @BeforeEach)

**Comment by rabelenda** [comment]
JVM system properties (same ones set with System.setProperty) can be set with java command line -D parameter (same as with jmeter command line). You may set them in you CI and spin up the jvm with such parameters. To avoid issues with __P and __property, we would need to provide a mechanism for setting them (like using JMeter utils or similar) and then you would need to implement some parameter parsing or similar in your tool to convert command line or file settings into java invocation of such elements before invoking the testplan. Or, if you actually think you need to specify the properties file we might implement some support for it, but sounds that previous approach (with system properties or with some api to set them) should be enough in most cases.

**Comment by kirillyu** [comment]
Yes, I understood that. And what about passing an array or other object from java code to Jmeter as in my scenario. Are there any options?

That is, now the Java code has nothing to do with the JVM of jmeter itself, because it is created in a separate space. And they cannot reuse each other's parts. Moreover, they cannot communicate with each other, except for the option with the generation of files that jmeter would read at startup

**Comment by kirillyu** [comment]
It's just that the functionality of java is lost in this case. It would be possible not to load jmeter with processing some things, and even more so with storage inside itself, but do it on the java side.

At first I thought it was one java machine and considered it a great advantage.

**Comment by rabelenda** [comment]
Hello,

> Yes, I understood that. And what about passing an array or other object from java code to Jmeter as in my scenario. Are there any options?

The only workaround that comes to my mind, until we implement some improvement (which we will), is the one I previously mentioned about using JSR223 elements with java code.

> That is, now the Java code has nothing to do with the JVM of jmeter itself, because it is created in a separate space. And they cannot reuse each other's parts. Moreover, they cannot communicate with each other, except for the option with the generation of files that jmeter would read at startup or at another moment

I don't follow your reasoning here. The Java code runs in same JVM as jmeter with the DSL while using embedded jmeter engine (the default one). Are you referring about the java code in the tool you previously mentioned you are implementing? I am a bit lost in what you mention in previous paragraph.

> It's just that the functionality of java is lost in this case. It would be possible not to load jmeter with processing some things, and even more so with storage inside itself, but do it on the java side.
> 
> At first I thought it was one java machine and considered it a great advantage.

I still not follow here. Maybe I confused your understanding of the DSL at some point? The JVM running jmeter is the same one used for running DSL code. If you need to pass parameters to the JVM you have to do it when you run the code that actually runs the DSL (eg: in maven surefire config, or in bash command line parameters when running the java command to run the tests). If you need to change system properties, you can use System.setProperty, but that only affects things that haven't read the properties still (things to execute in the "future").

Does this clarify anything? I am losing something? Did you thought that the DSL ran in one JVM and JMeter instance in another?

**Comment by kirillyu** [comment]
Hmm, yes I thought so. This is strange because in this case I do not understand why I did not see the property inside jmeter.  I'll try to import class into groovy and call java constructor from there. It should see the JVM name space

**Comment by rabelenda** [comment]
> I did not see the property inside jmeter

How you were trying to see the property? Debugging the code? using ${__P or ${__property? using groovy script inside JSR223 element?

**Comment by kirillyu** [comment]
I am talking about this:
```
public class PerfTest {

  public  class JDBCResult {
    public  int RowsCount;
    public   List<String> RowsValues = new ArrayList<>();

    class JDBCPostgreSQL {
      static final String DB_URL = "jdbc:postgresql://test/product";
      static final String USER = "test";
      static final String PASS = "test";
    }
    protected void JDBCResultBuilder() {
      Connection connection = null;
      try
      {
        connection = DriverManager
                .getConnection(JDBCPostgreSQL.DB_URL, JDBCPostgreSQL.USER, JDBCPostgreSQL.PASS);
      } catch(SQLException e) {
        System.out.println("Connection Failed");
        e.printStackTrace();
      }
      if(connection !=null) {
        System.out.println("You successfully connected to database now");
        try (Statement statement = connection.createStatement()) {
          ResultSet rs = statement.executeQuery("SELECT DISTINCT(product_set_id) FROM public.product WHERE product_set_id is NOT NULL");
          while (rs.next()) {
            this.RowsValues.add(rs.getString("product_set_id")); //or rs.getString(1); if you know the column is the first in the query's result
          }
          rs.close();
          statement.close();
          this.RowsCount = this.RowsValues.size();
        } catch (SQLException e) {
          System.out.println("Statement Failed");
          e.printStackTrace();
        }
      } else {
        System.out.println("Failed to make connection to database");
      }
    }
  }


  @BeforeEach
  public void setup() {
    JDBCResult current = new JDBCResult();
    current.JDBCResultBuilder();
    System.out.println(current.RowsCount);
  }



  @Test
  public void test() throws Exception {
    JDBCResult current = new JDBCResult();
    current.JDBCResultBuilder();
    System.out.println(current.RowsCount);
    TestPlanStats test = testPlan(
            threadGroup(1,1,
                    jsr223Sampler(
                            " System.out.println(current.RowsCount);\n" +
                            "    System.out.println(current.RowsValues.toString());")
            )
    ).run();
  }
```
The Jmeter get exception 
```groovy.lang.MissingPropertyException: No such property: current for class: Script1```

I tried to import this my package or class, but no result. If this is one JVM, I suggesed to see the objects that it has. 
Apparently I understand this incorrectly.

**Comment by kirillyu** [comment]
Finally I understood everything! :))
[This row](https://github.com/abstracta/jmeter-java-dsl/blob/master/jmeter-java-dsl/src/main/java/us/abstracta/jmeter/javadsl/core/engines/JmeterEnvironment.java#L43) defines which classes will be visible from JMeter. 

Locally I added my class (hardcode) and bingo there! Anywhere in the groove I can do import my.package. *
In this case, I can use what was previously done in Java. Reuse anything you want!
This is what I dreamed of!)

Probably I can make a revision that will create an interface in which you can add classes that I would like to use in JMeter (setter). So far I have implemented it locally.
What do we think about this feature?

**Comment by rabelenda** [comment]
Hello,

trying to understand your use case: were you using a class that was not part of the code of the project where you run the test? As far as I have experience the search path only needs to be altered when you want to add jars that are not already included in your project/classpath.

In the main scenarios where we have had to change search paths in the past are for jmeter functions to be visibile for jmeter runtime.

Can you provide an example to understand it better and potentially test it?

Thank you fo testing this and bringing this matter to attention.

Regards

**Comment by kirillyu** [comment]
No the class is the part of project. 
Are you saying that I need to pass this class to the search? It looks like you're right, apparently I came up with this problem :))))

I need to invest a couple of points in mindfulness ...

**Comment by kirillyu** [comment]
Problem!
If System.setProperty () passes a parameter inside the JVM as a -D argument, then we cannot take this property into Jmeter via $ {__ P} or props.get (). Jmeter only supports parameterization via -J.

In this regard, there is no way to uniformly handle properties both inside DSL and in Jmeter. All this is due to the fact that we do not have the ability to expose the property from the DSL so that JMeter can see it.

The supposed solution to the problem - you need to make the property setting similar to JMeter, or at least make it optional. Our implementation https://github.com/abstracta/jmeter-java-dsl/blob/66487e17f71e664ba239f5dc6279bf9045b52164/jmeter-java-dsl/src/main/java/us/abstracta/jnmeter/javadsl/core/engines/JavaEmeter L38

Whereas in Jmeter:
https://github.com/apache/jmeter/blob/c98be3f40009caffb8b66aded702356d975bb4d7/src/core/src/main/java/org/apache/jmeter/util/JMeterUtils.java#L194
we do not have a loadJMeterProperties method

**Comment by kirillyu** [comment]
Understood.
There are two methods in groovy: 'get' and 'getProperty'. And there are two JMeter functions: ('__P' and '__property'). Only the second method works in both scenatios. Simle get and __P - not working because properties class has two set of values: default ones and actual ones. When we set properties like System.setProperty (...) we set the default one, so in actual set it is not available. It is bug. Now we can use a working implementation

**Comment by LIFA-0808** [comment]
But '__P' is working too. Now only 'get' is doesn`t work.

**Comment by rabelenda** [comment]
I can confirm that `${__P()}` and `${__property()}` work. 

I originally thought they were not working but was due to some quoting issue in the test I was running. 

I have just verified and only `props[]` and `props.get()` are problematic since they use `HashTable#get` instead of `Properties#getProperty`. The current workaround is using `props.getProperty()` instead.

**Comment by rabelenda** [comment]
We just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.37) which allows [setting Jmeter properties](https://abstracta.github.io/jmeter-java-dsl/guide/#jmeter-properties) explicitly.
