### ISSUE TITLE
Counts Not Correct

### ISSUE THREAD

**Issue by MrThreepwood** [abstracta/jmeter-java-dsl#5]
I did a brief test with this DSL to check out how it works. While it does work fairly conveniently with the test shown, it doesn't seem to work correctly.

Using just the code from the docs I end up with 20 result lines in my JTL output, the stats.overall().sampleCount() is 16 and the errorCount() is 18. Obviously the URL http://my.service doesn't actually exist, so they should all be errors. Considering it runs 2 threads 10 times I would expect the error count to be 20 and the sample count to be 20. This is what appears in the .jtl file, I'm not sure why the programmatic results are different.

**Comment by MrThreepwood** [comment]
After running this a few more times I've gotten 20 for each MOST of the time, but not all. It looks like it may be a race condition in something? I don't know how the results are returned from this library. Is it reading the file that's generated?

```kotlin
        LogSettings.applySettings(true)
        LogSettings.applyLevels(mapOf("org.apache" to Level.WARN))
        val plan = testPlan(
                threadGroup(2, 10,
                        httpSampler("http://my.service")
                                .post("{\"name\": \"test\"}", MimeTypes.Type.APPLICATION_JSON)
                ),  //this is just to log details of each request stats
                jtlWriter("test.jtl")
        )

        var failures = 0
        repeat(10) {
            val stats = plan.run()
            if (stats.overall().samplesCount() != 20L || stats.overall().errorsCount() != 20L) failures++
        }
        logInfo { "The amounts did not match $failures times" }
```

Running the above code has the following ouput:
```
 =     20 in 00:00:01 =   34.3/s Avg:     4 Min:     0 Max:    37 Err:    20 (100.00%)
 =     20 in 00:00:00 =  465.1/s Avg:     0 Min:     0 Max:     1 Err:    20 (100.00%)
 =     20 in 00:00:00 =  392.2/s Avg:     1 Min:     0 Max:    10 Err:    20 (100.00%)
 =     20 in 00:00:00 =  400.0/s Avg:     0 Min:     0 Max:     1 Err:    20 (100.00%)
 =     20 in 00:00:00 =  434.8/s Avg:     0 Min:     0 Max:     1 Err:    20 (100.00%)
 =     20 in 00:00:00 =  363.6/s Avg:     0 Min:     0 Max:     1 Err:    20 (100.00%)
 =     20 in 00:00:00 =  384.6/s Avg:     0 Min:     0 Max:     1 Err:    20 (100.00%)
 =     20 in 00:00:00 =  400.0/s Avg:     0 Min:     0 Max:     1 Err:    20 (100.00%)
 =     20 in 00:00:00 =  344.8/s Avg:     0 Min:     0 Max:     1 Err:    20 (100.00%)
 =     20 in 00:00:00 =  444.4/s Avg:     0 Min:     0 Max:     1 Err:    20 (100.00%)
16:04:40.612 [main] INFO  a.b.t.a.loadtests.PerformanceTest - The amounts did not match 6 times
```
The amount of times that it doesn't match isn't always 6, but the log output seems to constantly say that 20 things were run with 20 errors and then the stats returned often don't match them.

**Comment by rabelenda** [comment]
Hello,

Thank you very much for reporting this issue!

We have just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.5.1) that should fix the problem you detected.

As far as we tested this version solves the issue, please let us know what you get after testing with this new version.

Regards

**Comment by MrThreepwood** [comment]
Yes, this has fixed it for me. Thanks for getting to this so quickly!
