### ISSUE TITLE
Able to use assertThat  instead of Jmeter Autostop plugin

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#50]
I'm not good in junit or in assertj lib, but I want to understand how it works. 

When I run the test assertion happens online or after the test runs?
Is it possible to do this online in such a way that it stops the test (or does some kind of logic)?

What I want? I am currently making a Quality Gate, which should work according to a number of parameters. For example, a certain request should fit into 99 percentiles in 1 second, there should be no more errors than a certain number. These requirements can be both for the entire test and for a specific request. And when they are not fulfilled, there is no point in driving the test further - this is a waste of time. We are working to ensure that stress testing has a minimal effect on the time to market. And this is the way to reduce this time.

The AutoStop plugin is not bad, but it is very poor in functionality. and it works according to logic that is not entirely suitable for me - it kills the jmeter process, and I need it to launch the tearDown thread group, which is a different standard (StopTest and not ShutDown as far as I remember).

**Comment by rabelenda** [comment]
Hello,

The way is currently designed you can use junit, assertj and other libs over TestPlanStats instance that is created after the test plan execution ends.

Really interesting question.

One option that comes to my mind is using a `jsr223PostProcessor`, collect stats on it and invoke `SampleResult.setStopThread(true)` when condition is met. You have to take into consideration centralized collection of statistics (which you may handle through some prop, or other mechanism that allows you to communicate and synchronize between threads). You may put the post processor at different levels of the test plan to take into consideration metrics for scope covered samplers (one sample, a set of samplers inside a thread group, at test plan level, etc).

I think that the ideal option would be to contribute to the AutoStop plugin and implement in the DSL support of it, but this also might requires more effort and might potentially face some road blocks if whatever you propose is not aligned with the plugin vision. Another option is implementing a new plugin, if you are blocked to contribute to AutoStop, but this requires even more effort. Another option, is implementing an abstraction directly in the DSL, but I think contributing to AutoStop would be preferable.

Let me know of your thoughts.

**Comment by kirillyu** [comment]
Contibuting my idea to AutoStop plugin makes there breaking chages, so it's not cool. I thing we need to implement JSR223 Listener for any extra cases wich any users would like to create in DSL. 
The PostProccessor doesn't have native work with jmeter batches of SamplerResult. I will research on it. Thanks for comment

**Comment by kirillyu** [comment]
My idea to configure the AutoStop based on non-functional requirements. There is no tests without requirements, so when we stop matching them, why we should to continue tests? 
But the requirements can be really different. 
- 99% of one operation is less than X
- 95% another operation is less than Y
- the total count of errors is less than Z
- the (elapsed-latency time (it's processing time on Jmeter side, or in another words  this is duration from the first byte of response to time when all postprocessors is done) is less than P
- Std. Dev is lower than ...

All of this cause the average is nothig)

**Comment by kirillyu** [comment]
maybe we can start test asynchronous and assert in circle?)) 😮

**Comment by rabelenda** [comment]
> Contibuting my idea to AutoStop plugin makes there breaking chages, so it's not cool.

What sort of non backwards compatible changes do you have in mind?



> I thing we need to implement JSR223 Listener for any extra cases wich any users would like to create in DSL.

Yes, this might be an option, and can be easily done. But I don't know if a listener is the best fit for your needs.





> The PostProccessor doesn't have native work with jmeter batches of SamplerResult.

What do you mean? Post processors, as listeners, apply to each sample result, they main difference that I see is purpose and how/when they execute. Are you refering to something like JMeter Backend Listeners instead of Jmeter native listeners?

I think you can implement all those requirements you list with a JSR223 Post processor as I mentioned. Maybe AutoStop doesn't have conditions for all, but maybe we can extend it?


> maybe we can start test asynchronous and assert in circle?)) 😮

What do you mean by this, it sounds really interesting, but would like to understand better what you mean.

All this discussion is really interesting, thank you to bring it to attention, and help evaluating alternatives.

**Comment by kirillyu** [comment]
Ok I will research and come back

**Comment by rabelenda** [comment]
@kirillyu how do you think we should continue in this matter?

**Comment by kirillyu** [comment]
No, I will close)
