### ISSUE TITLE
HTTP Sampler parametrization

### ISSUE THREAD

**Issue by LIFA-0808** [abstracta/jmeter-java-dsl#56]
Hi, thanks for the great tool you are developing.

I think the current implementation is missing important functionality:

1. It would be convenient to configure the URL from separate fields protocol, host, path, port. This will give more flexibility in building requests and using `RequestDefaults`.
2. When the URL splitting into components will added, it will be possible to implement adding individual parameters as components of the `HTTP Sampler` and add property `URL Encode?`

For example: 
https://example.com/any/path?key=va%20lue
> httpSampler("Hello Sampler").protocol("https").host("example.com").path("/any/path").addParameter("key","va lue", true)

3.  There is no `File Upload` functionality. 

It would be greate if u can add this.

**Comment by rabelenda** [comment]
Thank you very much for your words and request for features.

1. Can you give some examples that may be preferable to separate a url into parts instead of specify the url in just one field/method?
2. Yes, adding something like httpSampler().param(name, value) in similar fashion as JMeter which doesn't require you to manually encode or build a request body or query string, and supports parameterization (jmeter expressions). We will consider for a future release.
3. Totally :-), we will consider it for future release.

Thank you again.

**Comment by LIFA-0808** [comment]
I'm glad to know that my proposal seems important to you for implementation.
I am currently writing a test using this DSL and I am getting completely unreadable string.
Example: (as you can see I offten use ${var} - that`s because I have to url encode my params in preprocessor)

`httpSampler("SamplerName", "https://somehost.io/qwerty/qwsoqw/${somePath}?orgId=1&from=${datetimestart}&to=${datetimeend}&var-project=${project_name}&var-run=${cur_run}&panelId=${panelId}&var-data_source=${variable1}&var-namespace=${name_some_var}&var-Host='${__machineName()}'&width=1500&height=600"`

VS "as it could be":

httpSampler("SamplerName")
	.protocol("https")
	.host("somehost.io")
	.path("${somePath}")
	.addParameter("orgId","1")
	.addParameter("from","${datetimestart}")
	.addParameter("to","${datetimeend}")
	.addParameter("var-project","${project_name}")
	.addParameter("var-run","${cur_run}")
	.addParameter("panelId","${panelId}")
	.addParameter("var-variable1","variable1 variable1 variable1 variable1", true)
	.addParameter("var-name_some_var","name_some_var name_some_var name_some_var", true)
	.addParameter("var-Host,"${__machineName()}")
	.addParameter("width"","1500")
	.addParameter("height","600")

**Comment by rabelenda** [comment]
What do you think of something like this instead:

```
httpSampler("SamplerName", "https://somehost.io/${somePath}")
  .param("orgId", "1")
  .param("from", "${datetimestart}")
 ...
```

The main difference being to specify the protocol, host, port and path in url, and then query parameters in param method, instead of using a method for each part of the url?

**Comment by LIFA-0808** [comment]
This will definitely make life much easier, if the URLencode function is implemented also.

**Comment by kirillyu** [comment]
Partly comlited in this PR https://github.com/abstracta/jmeter-java-dsl/pull/61

**Comment by rabelenda** [comment]
Hello

We have just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.42) which includes [parameters](https://abstracta.github.io/jmeter-java-dsl/guide/#parameters), [multipart](https://abstracta.github.io/jmeter-java-dsl/guide/#multipart-requests) and [url parts](https://abstracta.github.io/jmeter-java-dsl/guide/#overriding-url-protocol-host-or-port) methods. Please let us know if this is enough for your needs or if you have any further comments on this regard.

Regards

**Comment by rabelenda** [comment]
I will close this, let me know if anything is missing and the issue needs to be reopened.
