### ISSUE TITLE
httpDefaults implementation

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#67]
It's really hard to use httpDefaults because of the methods now are different from httpRequest. And there is no way to set only port and protocol for example, so the .url method is not really usefull

**Comment by rabelenda** [comment]
Hello, thank you again for asking for such support.

Can you provide example where this usability issue arises?

Regards

**Comment by kirillyu** [comment]
for ex - you want to set everywhere protocol to https, after you see that your test has too much dublicates. you found the object httpDefaults, and trying to set there '. protocol', but you cant . you see the only URL setter. okay let's do it like .URL('https'), but doesn't work. why? okey you need to do it like this .url('https://'). clear. after that you see another think, the port method uses so many times too. okay let's specify it once and use everywhere. but you still have only . url() method. what you will do? okay let's try this . url('https://'+'8086')... not working. you got it?)

**Comment by rabelenda** [comment]
So, in general, the domain changes in requests, but protocol and port don't (or not so often)? 

In such scenario doing something like: `httpDefaults().url("https://mydefaultdomain:8080"), and then `httpSampler('/my_path').host('myHost')`.

Thank you for describing such scenario, but do you think that an example as the one I provided, and inciting users to use http defaults with a base/initial url and then overwrite the specific field in sampler when host, port and/or protocol changes, might be enough?

I understand that we could provide the methods for consistency and ease jmeter users, who already expect for such fields. I am trying to understand if there is actually a simpler/shortest way of modeling the same problem. For instance, I would in general think is preferable something like:

```java
httpDefaults()
  .url("http://myservice"),
httpSampler("/users"),
httpSampler("/products"),
httpSampler("/products")
  .protocol("https")
  .port(8081)
```
than following one, which requires more code and would in general be the way jmeter users would by default model it (I believe):
```
httpDefaults()
  .portocol("http")
  .host("myservice"),
httpSampler("/users"),
httpSampler("/products"),
httpSampler("/products")
  .protocol("https")
  .port(8081)
```

I am still pretty sure there is a case I haven't thought yet that would make more sense to use a format like the later than using the first approach.

What do you think? Maybe just to ease jmeter users is enough? but I would like to understand more about the scope.

**Comment by kirillyu** [comment]
i create the issue only when i faced with problem and discuss it with team. so there is real case with different host (few services and mock). my opinion is simple - similar objects should have similar methods.

**Comment by kirillyu** [comment]
but i am not really sure how implement it better :)

**Comment by rabelenda** [comment]
Hello,

We have added requested methods in [latest release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.49).

Please let us know if is what you expected.

Regards
