### ISSUE TITLE
Test manipulation buttons

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#68]
Debug now is hard. It is same for jmeter, but not totally. When we started the resultTreeVisualizer in DSL we see the request, if there are many requests it is hard to click on one of samplers. In Jmeter there is the stop button for it. Can we add the tool bar with buttons to dsl? Like .toolbar method or add it to visualisation window?

**Comment by rabelenda** [comment]
Interesting, 

I understand that you want to be able to stop test plan when you identify something that needs attention and don't want to continue. Do you actually want to stop the test plan in such scenarios? Or are you looking more like a Pause/Resume behavior? Or maybe both?

**Comment by kirillyu** [comment]
It works good! Cool, thank you!
