### ISSUE TITLE
GraphQL sampler feature request

### ISSUE THREAD

**Issue by MaksSieve** [abstracta/jmeter-java-dsl#85]
JMeter has graphql support since 5.4 version and internal classes could be used for implementation.

Proposed dsl:
```java
graphqlSampler("https://localhost:8080")
   .queryFromFile("query.graphql")
   .variable("a", test)
   .variable("b", test),
```

**Comment by rabelenda** [comment]
Hello, nice proposal! I think many users will benefit from such sampler, thank you for proposing this!

Regarding the proposed dsl, since query string is always needed to set, maybe makes more sense to have something like 

```java
  graphqlSampler("https://localhost:8080", "{user(id: 1) {name}}")
```
With variables and method name:
```java
String userQuery = "query UserQuery($id: Int) { user(id: $id) {name}}"
...
  graphqlSampler("https://localhost:8080", userQuery)
    .operationName("UserQuery")
    .variable("id", 1)
```

Would you usually use a file instead of just setting a string for the query? If you identify some significant benefit of such approach we may implement support for passing File instances if needed.

**Comment by MaksSieve** [comment]
thx for fast response)

agreed, your vision of signature is better.

wat about using files, in my opinion queries that are using in production are much bigger and complicated than we could imagine. and it's better to store them in separate files in resources folder than put long spaghetti in my code)

**Comment by rabelenda** [comment]
We internally use a TestResource class for the DSL internal tests which abstracts path resolution for resources (eg: in src/test/resources). We have discussed in the past with @kirillyu to make such class part of the public api of the dsl. With such addition you could use something like this:

```java
graphqlSampler("https://localhost:8080", new TestResource("/myQuery.graphql").getContents())
```
or if we provide a file interface in sampler method:

```java
graphqlSampler("https://localhost:8080", new TestResource("/myQuery.graphql").getFile())
```

What do you think?

**Comment by kirillyu** [comment]
I also need this functionality.  Thank you

**Comment by rabelenda** [comment]
Ok, great!,

We will work on this and consider it for next release. 

If anyone would like to take this and collaborate with a PR instead please let us know. We would really appreciate it.

Regards

**Comment by MaksSieve** [comment]
> We internally use a TestResource class for the DSL internal tests which abstracts path resolution for resources (ie: files in src/test/resources). We have discussed in the past with @kirillyu to make such class part of the public api of the dsl. With such addition you could use something like this:
> 
> ```java
> graphqlSampler("https://localhost:8080", new TestResource("/myQuery.graphql").getContents())
> ```
> 
> or if we provide a file interface in sampler method:
> 
> ```java
> graphqlSampler("https://localhost:8080", new TestResource("/myQuery.graphql").getFile())
> ```
> 
> What do you think?

I think it would be more convenient and readble to use special methods such `.bodyFromFile()` with some magic of getting resources inside.

**Comment by MaksSieve** [comment]
I have an implementation of graphqlSampler that just extends httpSampler, is it right way to do so?) If it is, I can push it an make PR.
Also i have a problem with body. Im creating it using GraphQLRequestParams from JMeter (`org.apache.jmeter.protocol.http.config`), but interpolation of parameters (i.e. from `csvDataSet`) doesnt work.
