### ISSUE TITLE
Need getters for BaseTestElement

### ISSUE THREAD

**Issue by MaksSieve** [abstracta/jmeter-java-dsl#87]
Im trying to implement WeighedSwitchController for java-dsl, and using com.blazemeter.jmeter.control.WeightedSwitchController as base and example. But it's impossible to take childrens' names from BaseTestElement to configure controller properly.

TestElement in JMeter itself has getters,  so i think it makes sense to add them in dsl implementation.

**Comment by kirillyu** [comment]
You can use java reflection to make this field gettable (accessible == true)

**Comment by kirillyu** [comment]
But i agree that getters implementation needed :)
